FROM golang:1.26.1-alpine

WORKDIR /workspace

RUN apk --no-cache add bash git curl make

ARG SQLC_VERSION=v1.28.0
ARG MIGRATE_VERSION=v4.18.3
ARG GOLANGCI_LINT_VERSION=v1.64.8

RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@${SQLC_VERSION} && \
    go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@${MIGRATE_VERSION} && \
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@${GOLANGCI_LINT_VERSION}

ENV PATH="/go/bin:${PATH}"

CMD ["sh"]
